// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createGreeting = `-- name: CreateGreeting :one
INSERT INTO greetings (name, message, emoji) VALUES ($1, $2, $3) RETURNING created_at, emoji, id, message, name
`

type CreateGreetingParams struct {
	Name    string
	Message string
	Emoji   string
}

func (q *Queries) CreateGreeting(ctx context.Context, arg CreateGreetingParams) (Greeting, error) {
	row := q.db.QueryRowContext(ctx, createGreeting, arg.Name, arg.Message, arg.Emoji)
	var i Greeting
	err := row.Scan(
		&i.CreatedAt,
		&i.Emoji,
		&i.ID,
		&i.Message,
		&i.Name,
	)
	return i, err
}

const listGreetings = `-- name: ListGreetings :many
SELECT created_at, emoji, id, message, name FROM greetings ORDER BY created_at DESC LIMIT 20
`

func (q *Queries) ListGreetings(ctx context.Context) ([]Greeting, error) {
	rows, err := q.db.QueryContext(ctx, listGreetings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Greeting
	for rows.Next() {
		var i Greeting
		if err := rows.Scan(
			&i.CreatedAt,
			&i.Emoji,
			&i.ID,
			&i.Message,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
