// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package api

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

func Dashboard(port int, status Status) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><title>Cheetah Dashboard</title><meta charset=\"utf-8\"><style>\n\t\t\t\tbody { font-family: system-ui, sans-serif; margin: 2rem; background: #0a0a0a; color: #e0e0e0; }\n\t\t\t\th1 { color: #f0f0f0; }\n\t\t\t\t.status { background: #1a1a2e; padding: 1rem; border-radius: 8px; margin-bottom: 2rem; }\n\t\t\t\t.status span { margin-right: 2rem; }\n\t\t\t\t.dot { display: inline-block; width: 10px; height: 10px; border-radius: 50%; margin-right: 4px; }\n\t\t\t\t.dot.on { background: #4ade80; }\n\t\t\t\t.dot.off { background: #ef4444; }\n\t\t\t\ttable { width: 100%; border-collapse: collapse; }\n\t\t\t\tth, td { text-align: left; padding: 0.5rem 1rem; border-bottom: 1px solid #2a2a3e; }\n\t\t\t\tth { color: #888; font-weight: 500; font-size: 0.85rem; text-transform: uppercase; }\n\t\t\t\ttr:hover { background: #1a1a2e; }\n\t\t\t\t.active-port { color: #4ade80; font-weight: 600; }\n\t\t\t\ta { color: #7dd3fc; text-decoration: none; }\n\t\t\t\ta:hover { text-decoration: underline; }\n\t\t\t\tcode { background: #1a1a2e; padding: 2px 6px; border-radius: 4px; font-size: 0.85rem; }\n\t\t\t\t.empty { text-align: center; padding: 3rem; color: #666; }\n\t\t\t</style></head><body><h1>Cheetah</h1><div class=\"status\" id=\"status-bar\"><span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if status.PostgresRunning {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<span class=\"dot on\"></span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<span class=\"dot off\"></span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "Postgres :")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprint(status.PostgresPort))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard.templ`, Line: 39, Col: 48}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</span> <span>Apps: <span id=\"app-count\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprint(status.AppCount))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard.templ`, Line: 41, Col: 66}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span></span></div><div id=\"app-table\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(dashboardJS).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<script src=\"/spaces.js\" data-space=\"cheetah\" data-port=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprint(port))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `dashboard.templ`, Line: 45, Col: 77}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

const dashboardJS = `<script>
(function() {
  const table = document.getElementById("app-table");
  const countEl = document.getElementById("app-count");
  let apps = {};

  function render() {
    const list = Object.values(apps);
    countEl.textContent = list.length;
    if (list.length === 0) {
      table.innerHTML = '<div class="empty">No apps registered. Run <code>go run main.go</code> in a child app to register.</div>';
      return;
    }
    let h = '<table><thead><tr>' +
      '<th>Space</th><th>Config</th>' +
      '<th>Blue</th><th>Green</th>' +
      '<th>Watch</th><th>Logs</th></tr></thead><tbody>';
    for (const a of list) {
      const watch = (a.watch.match || []).map(p => '<code>' + p + '</code>').join(' ');
      const p1cls = a.ports.active === a.ports.blue ? ' class="active-port"' : '';
      const p2cls = a.ports.active === a.ports.green ? ' class="active-port"' : '';
      h += '<tr>' +
        '<td><strong><a href="' + location.protocol + '//' + a.space + '.localhost:' + location.port + '/">' + a.space + '</a></strong></td>' +
        '<td>' + (a.config || []).map(c => '<code>' + c + '</code>').join(' ') + '</td>' +
        '<td' + p1cls + '>:' + a.ports.blue + '</td>' +
        '<td' + p2cls + '>:' + a.ports.green + '</td>' +
        '<td>' + watch + '</td>' +
        '<td>' + (a.logs || []).length + '</td></tr>';
    }
    h += '</tbody></table>';
    table.innerHTML = h;
  }

  const es = new EventSource("/api/events");

  es.addEventListener("init", function(e) {
    const list = JSON.parse(e.data);
    apps = {};
    for (const a of list) apps[a.space] = a;
    render();
  });

  es.addEventListener("app", function(e) {
    const a = JSON.parse(e.data);
    apps[a.space] = a;
    render();
  });

  es.addEventListener("deregister", function(e) {
    const data = JSON.parse(e.data);
    delete apps[data.space];
    render();
  });

  render();
})();
</script>`

var _ = templruntime.GeneratedTemplate
