// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Greeting struct {
	ID        int32
	Name      string
	Message   string
	CreatedAt time.Time
	Emoji     string
}
