// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (name, value) VALUES ($1, $2) RETURNING created_at, id, name, value
`

type CreateItemParams struct {
	Name  string
	Value string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem, arg.Name, arg.Value)
	var i Item
	err := row.Scan(
		&i.CreatedAt,
		&i.ID,
		&i.Name,
		&i.Value,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT created_at, id, name, value FROM items WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id int32) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.CreatedAt,
		&i.ID,
		&i.Name,
		&i.Value,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT created_at, id, name, value FROM items ORDER BY created_at DESC
`

func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.CreatedAt,
			&i.ID,
			&i.Name,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
